accounts/urls.py
from django.urls import path

from products.views import UserProductHistoryView
from .views import AccountHomeView, AccountEmailActivationView, UserDetailUpdateView


urlpatterns = [
    path('', AccountHomeView.as_view(), name='home'),
    path('details/', UserDetailUpdateView.as_view(), name='user-update'),
    path('history/products/', UserProductHistoryView.as_view(), name='user-product-history'),
    path('email/confirm/<key>/', AccountEmailActivationView.as_view(), name='email-activate'),
    path('email/resend-activation/', AccountEmailActivationView.as_view(), name='resend-activation'),
]

carts/urls.py
from django.urls import path

from .views import (cart_home,
                    cart_update,
                    checkout_home,
                    checkout_done_view)

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('checkout/success/', checkout_done_view, name='success'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.views import LogoutView

from accounts.views import LoginView, RegisterView, GuestRegisterView
from addresses.views import (AddressCreateView,
                             AddressListView,
                             AddressUpdateView,
                             checkout_address_create_view,
                             checkout_address_reuse_view)
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_create_view
from carts.views import cart_detail_api_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebHookView
from orders.views import LibraryView
from . import views


urlpatterns = [
    path('', views.home_page, name='home'),
    path('admin/', admin.site.urls),
    # path('about/', views.about_page, name='about'),
    # path('contact/', views.contact_page, name='contact'),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include(('accounts.urls', 'account'), namespace='account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('address/', RedirectView.as_view(url='/addresses')),
    path('addresses/', AddressListView.as_view(), name='addresses'),
    path('addresses/create/', AddressCreateView.as_view(), name='address-create'),
    path('addresses/<pk>/', AddressUpdateView.as_view(), name='address-update'),
    path('analytics/sales/', SalesView.as_view(), name='sales-analytics'),
    path('analytics/sales/data/', SalesAjaxView.as_view(), name='sales-analytics-data'),
    path('login/', LoginView.as_view(), name='login'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('register/guest/', GuestRegisterView.as_view(), name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('cart/', include(('carts.urls', 'cart'), namespace='cart')),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('billing/payment-method/create/', payment_method_create_view, name='billing-payment-method-endpoint'),
    path('register/', RegisterView.as_view(), name='register'),
    path('library/', LibraryView.as_view(), name='library'),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('search/', include(('search.urls', 'search'), namespace='search')),
    path('settings/', RedirectView.as_view(url='/account')),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebHookView.as_view(), name='webhooks-mailchimp'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import OrderListView, OrderDetailView, VerifyOwnerShip


urlpatterns = [
    path('', OrderListView.as_view(), name='list'),
    path('endpoint/verify/ownership/', VerifyOwnerShip.as_view(), name='verify-ownership'),
    path('<order_id>/', OrderDetailView.as_view(), name='detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>eCommerce Rocha</title>
    <!--<link rel='stylesheet' href='{% static "css/css.html" %}' >-->
    <!--<link rel="script" href="{% static 'js/js.html' %}">-->
    {% include 'base/css.html' %}
  </head>
  <body>

    {% include 'navbar.html' with brand_name='eCommerce' %}
    <div class="container">
      {% if messages %}
        <div class="alert alert-success messages">
          {% for message in messages %}
            <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }} <br/>
            </span>
          {% endfor %}
        </div>
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>

    {% include 'base/js.html' %}
    {% block javascript %}
    {% endblock %}

  </body>
</html>

templates/home_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class='text-center'>
      <h1>{{ title }}</h1>
      <h1>Hello, world we're working!</h1>
    </div>

    <div class='row'>
      <div class='col'>
          <img src="{% static 'img/mugiwaras_flag.png' %}" class='img-fluid' />
          <p>{{ welcome }}</p>
      </div>
    </div>
    {% if request.user.is_authenticated %}
    <div class='row'>
      <div class='col'>
      <h1>Premium</h1>
      {{ premium_content }}
      </div>
    </div>
    {% endif %}

{% endblock %}

templates/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'marketing-pref' as mkt_pref_url %}
{% url 'account:home' as account_url %}
{% url 'cart:home' as cart_url %}
{% url 'account:user-product-history' as user_history_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
    <a class="navbar-brand" href="{{ home_url }}">
        <img src="//getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" width="30" height="30"
             class="d-inline-block align-top" alt="">
        {% if brand_name %}
          {{ brand_name }}
        {% else %}
          Ian eCommerce
        {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item {% if request.path == home_url %} active {% endif %}">
          <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == products_list_url %} active {% endif %}">
          <a class="nav-link" href="{{ products_list_url }}">Products</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item {% if request.path == account_url %} active {% endif %}" href="{{ account_url }}">Home</a>
            <a class="dropdown-item" href="{{ account_url }}#billing">Billing</a>
            <a class="dropdown-item" href="{{ user_history_url }}">History</a>
            <a class="dropdown-item" href="{% url 'library' %}">Library</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == register_url %} active {% endif %}">
          <a class="nav-link" href="{{ register_url }}">Register</a>
        </li>
        <li class="nav-item {% if request.path == login_url %} active {% endif %}">
          <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
          <a class="nav-link" href="{{ cart_url }}">
            <span class="navbar-cart-count">{{ request.session.cart_items }}</span>
            <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
        </li>
      </ul>

      {% include 'search/snippets/search-form.html' %}
    </div>
  </div>
</nav>